language: generic

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    # - EMACS_VERSION=25.3 # <- we need to install org-plus-contrib, the bundled version is to old
    - EMACS_VERSION=26.1
    - EMACS_VERSION=master

matrix:
  allow_failures:
    - env: EMACS_VERSION=master

install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version

script:
  make all EMACS=${EMACS}
